In [5]:
import tensorflow as tf
import numpy as np
width = tf.placeholder('int32', name='width')
height = tf.placeholder('int32', name='height')
area = tf.multiply(width,height, name='area')  

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('area=',sess.run(area,feed_dict={width: 6, height: 8}))

area= 48


In [5]:
tf.summary.merge_all()  #整合要顯示的資料
train_writer = tf.summary.FileWriter('log/area',sess.graph)   #主要寫入當前執行目錄下的log/area子目錄

In [6]:
x = tf.Variable([0, 1, 0.5, 0.6])  #一維
y = tf.Variable([[0, 1, 0.5, 0.6],[0.4, 1, 2, 0.7],[0.2, 2, 9, 0.2]])  #二維

In [7]:
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X = sess.run(x)
    Y = sess.run(y)
    print(X,'X shape:',X.shape)
    print(Y,'Y shape:',Y.shape)

[0.  1.  0.5 0.6] X shape: (4,)
[[0.  1.  0.5 0.6]
 [0.4 1.  2.  0.7]
 [0.2 2.  9.  0.2]] Y shape: (3, 4)


In [8]:
X = tf.Variable([[1., 1., 1.]])
W = tf.Variable([[-0.5, -0.2], [-0.3,  0.4], [-0.5,  0.2]])
b = tf.Variable([[0.1, 0.2]])
XWb = tf.matmul(X, W)+b

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('XWb:',sess.run(XWb))

XWb: [[-1.1999999  0.6      ]]


# 矩陣運算模擬神經網路

In [2]:
X = tf.Variable([[0.4, 0.2, 0.4]])
W = tf.Variable([[-0.5, -0.2],[-0.3,  0.4],[-0.5,  0.2]])
b = tf.Variable([[0.1, 0.2]])
XWb = tf.matmul(X,W)+b
y = tf.nn.relu(XWb)

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('XWb:');print(sess.run(XWb))
    print('y:');print(sess.run(y))

Instructions for updating:
Colocations handled automatically by placer.
XWb:
[[-0.36000004  0.28      ]]
y:
[[-0.    0.28]]


In [6]:
X = tf.placeholder('float', [None, 3])
W = tf.Variable(tf.random_normal([3, 2]))
b = tf.Variable(tf.random_normal([1, 2]))
XWb = tf.matmul(X,W)+b
y = tf.nn.relu(XWb)

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X_array = np.array([[0.4, 0.2, 0.4]])
    (_b, _W, _X, _y) = sess.run((b, W, X, y), feed_dict={X:X_array})
    print('_b:',_b,', _W:',_W,', _X:',_X,', _y:',_y)

_b: [[0.21782006 1.5617473 ]] , _W: [[0.7040635  0.6768398 ]
 [1.2828304  1.3779947 ]
 [0.75585127 0.07535274]] , _X: [[0.4 0.2 0.4]] , _y: [[1.058352  2.1382232]]


In [11]:
def layer(output_dim, input_dim, inputs, activation=None):
    W = tf.Variable(tf.random_normal([input_dim, output_dim]))
    b = tf.Variable(tf.random_normal([1, output_dim]))
    XWb = tf.matmul(inputs, W)+b
    if activation is None:
        outputs = XWb
    else:
        outputs = activation(XWb)
    return outputs

In [13]:
X = tf.placeholder('float', [None, 4])
h = layer(output_dim = 3, input_dim = 4, inputs = X, activation = tf.nn.relu)
y = layer(output_dim = 2, input_dim = 3, inputs = h)

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X_array = np.array([[0.4, 0.2, 0.4, 0.5]])
    (layer_X, layer_h, layer_y) = sess.run((X, h, y), feed_dict = {X:X_array})
    print('input layer X:', layer_X)
    print('hidden layer h:', layer_h)
    print('output layer y:', layer_y)

input layer X: [[0.4 0.2 0.4 0.5]]
hidden layer h: [[-0.          0.34691143 -0.        ]]
output layer y: [[-1.6438627  2.350263 ]]


In [15]:
def layer_debug(output_dim, input_dim, inputs, activation=None):
    W = tf.Variable(tf.random_normal([input_dim, output_dim]))
    b = tf.Variable(tf.random_normal([1, output_dim]))
    XWb = tf.matmul(inputs, W)+b
    if activation is None:
        outputs = XWb
    else:
        outputs = activation(XWb)
    return outputs,W,b

In [17]:
X = tf.placeholder('float', [None, 4])
h,W1,b1 = layer_debug(output_dim = 3, input_dim = 4, inputs = X, activation = tf.nn.relu)
y,W2,b2 = layer_debug(output_dim = 2, input_dim = 3, inputs = h)

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X_array = np.array([[0.4, 0.2, 0.4, 0.5]])
    (layer_X, layer_h, layer_y,W1,b1,W2,b2) = sess.run((X, h, y,W1,b1,W2,b2), feed_dict = {X:X_array})
    print('input layer X:', layer_X,sep='\n')
    print('W1:',W1,sep='\n')
    print('b1:',b1,sep='\n')
    print('hidden layer h:', layer_h,sep='\n')
    print('W2:',W2,sep='\n')
    print('b2:',b2,sep='\n')
    print('output layer y:', layer_y,sep='\n')

input layer X:
[[0.4 0.2 0.4 0.5]]
W1:
[[ 0.3917903   1.3356526  -0.37661743]
 [ 0.45549446  0.9890086  -0.558655  ]
 [ 0.95031995  1.072156   -0.68911016]
 [-1.4255245  -0.8459974  -0.00843623]]
b1:
[[-0.66267675  1.6835241   0.6696364 ]]
hidden layer h:
[[-0.          2.4214506   0.12739629]]
W2:
[[-0.13075495  0.83973515]
 [-0.94018686  0.22271502]
 [ 0.9454406  -0.30547047]]
b2:
[[0.99103767 0.26588172]]
output layer y:
[[-1.1651328  0.7662593]]
